{
 "title": "a9s Metrics Sample",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_user{application_name=\"a9s-metrics-example\",cpu=\"cpu-total\"}  "
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cgroup_memory_usage_in_bytes{application_name=\"a9s-metrics-example\"}  "
    }
   ]
  },
  {
   "title": "Operations Processed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_a9s_metrics_sample_ops_total{application_name=\"a9s-metrics-example\"}"
    }
   ]
  },
  {
   "title": "Random Number",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_a9s_metrics_sample_random_number{application_name=\"a9s-metrics-example\"}"
    }
   ]
  }
 ]
}